# Generated by Django 2.2 on 2021-08-16 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_icecream_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_cost',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
